{
   "config_path": "pipelines/FinaBP17.json", 
   "description": "Add some custom description for this pipeline!", 
   "id": "4", 
   "name": "FinaBP17", 
   "notebooks": [
      {
         "is_clone": "no", 
         "kernel_type": "py3-env", 
         "name": "EventAnalyzerFINA", 
         "path": "ipython/EventAnalyzerFINA.ipynb", 
         "pipeline_status": "off", 
         "type": "Analyzer"
      }, 
      {
         "is_clone": "no", 
         "kernel_type": "py3-env", 
         "name": "DunaArenaGeolocation", 
         "path": "ipython/DunaArenaGeolocation.ipynb", 
         "pipeline_status": "on", 
         "type": "Experiment"
      }, 
      {
         "is_clone": "no", 
         "kernel_type": "py3-env", 
         "name": "FINAGeolocation", 
         "path": "ipython/FINAGeolocation.ipynb", 
         "pipeline_status": "on", 
         "type": "Experiment"
      }
   ], 
   "reports": [
      {
         "date": "2017-07-19", 
         "id": "geolocation_experiments_2017-07-19", 
         "kernel_status": "active", 
         "name": "geolocation experiments",
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      },
      {
         "date": "2017-07-19", 
         "id": "geolocation_experiments_2017-07-19", 
         "kernel_status": "active", 
         "name": "geolocation experiments", 
         "date": "2017-07-17", 
         "id": "failures_2017-07-17", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-14", 
         "id": "failures_2017-07-14", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-13", 
         "id": "failures_2017-07-13", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-12", 
         "id": "failures_2017-07-12", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))\n\nMost csak eng \u00e9s budapest halt meg.", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-11", 
         "id": "failures_2017-07-11", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-10", 
         "id": "failures_2017-07-10", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-05", 
         "id": "failures_2017-07-05", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-04", 
         "id": "failures_2017-07-04", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-03", 
         "id": "failures_2017-07-03", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }
   ]
}